### ISSUE TITLE
function for constraint evaluation

### ISSUE THREAD

**Issue by kibaekkim** [exanauts/ActiveSetMethods#30]
`eval_g` evaluates the constraint body (e.g., left-hand side), excluding the evaluation of the right-hand side. Was that intended?

**Comment by ssadat** [comment]
yes, the eval_g works together with constraint_lb and constraint_ub. This is the format that was used by Ipopt and I followed the same format.

**Comment by kibaekkim** [comment]
My colleague also confirmed that too. Thanks!
