### ISSUE TITLE
merit function evaluation

### ISSUE THREAD

**Issue by kibaekkim** [exanauts/ActiveSetMethods#33]
When evaluating $\phi(x_k+\alpha p_k; \mu)$, $\| c_k \|$ is not updated at $x_k + \alpha p_k$; that is, $\| c_k \|$ evaluated at $x_k$ is used.

**Comment by ssadat** [comment]
@kibaekkim I check it and if you are referring to the one inside inner while loop (step size calculation) the phi_x_p is taking norm_E_a as an argument which is considering | c_(k+1) |. If not, can you refer the line number so I can check it
